- README.md
- helm/templates/deployment.yaml
Agent ID will be generated directly when the Agent
is registered against the server.
> Remove agent id from environment values

- helm/Chart.yaml
- helm/templates/pod_disruption_budget.yaml
Added matchLabels for pod_disruption_budget template.
Changed appVersion to include the "v" or else the default won't be able to correctly pull the image either
> PDB template needs matchLabels.

- README.md
- helm/Chart.yaml
- helm/values.yaml
Other changes:
- bumps the chart and app versions to latest
- removes the deprecated reference to agentId in helm values, which fixes issue #13
> Add agent environment configuration to docs

- helm/templates/deployment.yaml
- helm/values.yaml
With this change, if there are `n` replicas of the agent running and a rolling upgrade is initiated, `n` replicas will always be running and available throughout the upgrade process.
Additionally, when Kubernetes issues a `SIGTERM` to the pod upon termination, the agent will be allowed to complete any inflight HTTP requests and scheduled jobs. The grace period allowed is dictated by a configurable Helm variable.
> configure highly available rolling upgrade with graceful agent shutdown

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.33.0.
> [CI] Bump OPA version in chart to v0.33.0

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.35.0.
> [CI] Bump OPA version in chart to v0.35.0

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.36.0.
> [CI] Bump OPA version in chart to v0.36.0

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.38.0.
> [CI] Bump OPA version in chart to v0.38.0

- helm/Chart.yaml
This PR bumps the chart version to 0.25.0, with which come the new agent platform architecture becomes available
> Bump chart version

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.41.0.
> [CI] Bump OPA version in chart to v0.41.0

- helm/Chart.yaml
- helm/templates/deployment-controller.yaml
- helm/templates/deployment-worker.yaml
- helm/templates/serviceaccount.yaml
- helm/values.yaml
This allows users to configure annotations against their OPA workloads to leverage authentication methods such as kube2iam or service account token volume projection.
> add service account creation and annotations

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.42.0.
> [CI] Bump OPA version in chart to v0.42.0

- helm/Chart.yaml
- helm/templates/ingress-controller.yaml
- helm/templates/pdb-controller.yaml
- helm/templates/pdb-worker.yaml
This makes the chart incompatible with Helm 2 but that's since gone EOL in 2020: https://github.com/helm/helm/releases/tag/v2.17.0
> Stop using deprecated helm capabilities attribute

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.43.0.
> [CI] Bump OPA version in chart to v0.43.0

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.44.0.
> [CI] Bump OPA version in chart to v0.44.0

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.45.0.
> [CI] Bump OPA version in chart to v0.45.0

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.46.0.
> [CI] Bump OPA version in chart to v0.46.0

- helm/Chart.yaml
- helm/templates/_helpers.tpl
- helm/templates/deployment-controller.yaml
- helm/templates/deployment-worker.yaml
We used to limit heapsize to half the allocated memory but this is not really needed anymore since workers are broken out of the service.
> remove heapsize limit on agent

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.47.0.
> [CI] Bump OPA version in chart to v0.47.0

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.48.0.
> [CI] Bump OPA version in chart to v0.48.0

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.52.0.
> [CI] Bump OPA version in chart to v0.52.0

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.53.0.
> [CI] Bump OPA version in chart to v0.53.0

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.55.0.
> [CI] Bump OPA version in chart to v0.55.0

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.56.0.
> [CI] Bump OPA version in chart to v0.56.0

- .github/workflows/deploy-chart.yml
This makes use of an updated version of a forked github action, where we are now affixing versions of helm plugins. Currently, the latest version of `helm-s3` plugin is broken, and so in the action itself, we are affixing to an older version that was known to work.
> Bump helm-release-version to leveraged working versions upstream plugins

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.57.0.
> [CI] Bump OPA version in chart to v0.57.0

- helm/templates/ingress-controller.yaml
- helm/values.yaml
This allows users to define paths in the following ways, where the path type defaults to `ImplementationSpecific` unless overriden by the specification of a `pathType`
```
paths:
- path: /agent
pathType: Prefix
- /health
- path: /dummy
```
> Add support for specific path type in ingress object

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.58.0.
> [CI] Bump OPA version in chart to v0.58.0

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.59.0.
> [CI] Bump OPA version in chart to v0.59.0

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.60.0.
> [CI] Bump OPA version in chart to v0.60.0

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.61.0.
> [CI] Bump OPA version in chart to v0.61.0

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.62.0.
> [CI] Bump OPA version in chart to v0.62.0

- helm/Chart.yaml
- helm/templates/deployment-worker.yaml
Without this, any custom fleets are disabled by default unless `enabled: true` is set.
> Default fleet enabled to true

- docker/compose.yaml
We adopt Traefik and Letsencrypt to provide supports for https in OPA
The new docker compose file is compatible with existing installation guide.
In order to enable https, users need to provide 2 extra environment variables
- SUPERBLOCKS_PROXY_ADMIN_EMAIL
- SUPERBLOCKS_PROXY_REPLICA_COUNT, default: 0, assign it to 1 to enable https proxy.
> Use Traefik and Letsencrypt to support https

- docker/compose.yaml
This should be handled better when we eventually have a script and in-app optional selection
> Default letsencrypt email address to an empty string

- scripts/README.md
- scripts/quickstart.sh
Implemented a script for installing docker and launching OPA on VMs
Tested on EC2/AmazonLinux and EC2/Ubuntu
A README.md file is also added to explain the usage.
> Add quickstart.sh for OPA deployment on VMs

- docker/compose.yaml
This ensures containers will restart unless explicitly removed or stopped by the user.
> Update default restart policy

- scripts/distro-test/amzn/Dockerfile
- scripts/distro-test/centos/Dockerfile
- scripts/distro-test/debian/Dockerfile
- scripts/distro-test/ubuntu/Dockerfile
Added docker files to test installation of docker and superblocks quickstart script in 4 linux distributions.
- AmazonLinux
- CentOS
- Debian
- Ubuntu
> Add distro docker test files for quickstart.sh

- .github/workflows/deploy-chart.yml
This makes it so that the github workflow to release a new chart only triggers on changes to the helm dir
> Only trigger chart release on helm changes

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.66.0.
> [CI] Bump OPA version in chart to v0.66.0

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.67.0.
> [CI] Bump OPA version in chart to v0.67.0

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.69.0.
> [CI] Bump OPA version in chart to v0.69.0

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.71.0.
> [CI] Bump OPA version in chart to v0.71.0

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.72.0.
> [CI] Bump OPA version in chart to v0.72.0

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.74.0.
> [CI] Bump OPA version in chart to v0.74.0

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.75.0.
> [CI] Bump OPA version in chart to v0.75.0

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.77.0.
> [CI] Bump OPA version in chart to v0.77.0

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.78.0.
> [CI] Bump OPA version in chart to v0.78.0

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.79.0.
> [CI] Bump OPA version in chart to v0.79.0

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.80.0.
> [CI] Bump OPA version in chart to v0.80.0

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.84.0.
> [CI] Bump OPA version in chart to v0.84.0

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.86.0.
> [CI] Bump OPA version in chart to v0.86.0

- README.md
We are now allowing Agents to connect to our 2 regions (us|eu) via this data domain configuration.
> Add data domain instructions to readme

- helm/templates/extra-manifests.yaml
- helm/values.yaml
This PR is being raised to allow additional resources to be injected in as part of the helm release. 
Kubernetes configurations can differ quite significantly from cluster to cluster and this PR provides the flexibility to add any additional resources users may require in their configuration.
> Add in the ability to inject in additional resources 

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.87.0.
> [CI] Bump OPA version in chart to v0.87.0

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.91.0.
> [CI] Bump OPA version in chart to v0.91.0

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.93.0.
> [CI] Bump OPA version in chart to v0.93.0

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.96.0.
> [CI] Bump OPA version in chart to v0.96.0

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.97.0.
> [CI] Bump OPA version in chart to v0.97.0

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.98.0.
> [CI] Bump OPA version in chart to v0.98.0

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.99.0.
> [CI] Bump OPA version in chart to v0.99.0

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.101.0.
> [CI] Bump OPA version in chart to v0.101.0

- helm/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v0.104.0.
> [CI] Bump OPA version in chart to v0.104.0

- helm/v2/Chart.yaml
- helm/v2/values.yaml
This officially releases the v2.0.0 version of our helm chart to support the control flow compatible agent.
> Bump the chart version

- helm/v2/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v1.0.2.
> [CI] Bump OPA version in chart to v1.0.2

- helm/v2/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v1.0.5.
> [CI] Bump OPA version in chart to v1.0.5

- scripts/distro-test/amzn/Dockerfile
Curl comes pre-installed in the latest amazonlinux base images
> Fix amazonlinux image build

- helm/v2/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v1.0.11.
> [CI] Bump OPA version in chart to v1.0.11

- helm/v2/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v1.0.14.
> [CI] Bump OPA version in chart to v1.0.14

- helm/v2/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v1.0.15.
> [CI] Bump OPA version in chart to v1.0.15

- helm/v2/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v1.1.1.
> [CI] Bump OPA version in chart to v1.1.1

- helm/v2/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v1.1.2.
> [CI] Bump OPA version in chart to v1.1.2

- helm/v2/Chart.yaml
- helm/v2/templates/deployment.yaml
- helm/v2/values.yaml
These limits apply to the JS /  Python workers as well, so need to be env variables.
Also, Helm converts the values to scientific notation resulting  in: 
`invalid argument "1e+08" for "--grpc.msg.req.max" flag: strconv.ParseInt: parsing "1e+08": invalid syntax`
Add int64 type to fix that.
> Pass grpc limits as environment variables and parse as ints

- helm/v2/templates/service.yaml
- helm/v2/values.yaml
Service Annotations for the OPA allow GKE users to add NEG and Backend Config annotations for configuring GCE ingress.
> Support Service Annotations

- helm/v2/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v1.3.2.
> [CI] Bump OPA version in chart to v1.3.2

- helm/v2/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v1.4.3.
> [CI] Bump OPA version in chart to v1.4.3

- helm/v2/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v1.5.0.
> [CI] Bump OPA version in chart to v1.5.0

- helm/v2/Chart.yaml
- helm/v2/templates/deployment.yaml
- helm/v2/values.yaml
Fixes #250 
The agent takes a while for `/health` to return successful. This is because we wait for all subprocess to be completely healthy. We might want to consider using a different success criteria for liveness that differs from the one used for readiness but for now, we'll just introduce a configurable delay. This should reduce/remove the flakiness on pod startup.
> make various values of liveness probe configurable

- helm/v2/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v1.6.1.
> [CI] Bump OPA version in chart to v1.6.1

- helm/v2/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v1.7.0.
> [CI] Bump OPA version in chart to v1.7.0

- helm/v2/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v1.7.1.
> [CI] Bump OPA version in chart to v1.7.1

- helm/v2/Chart.yaml
- helm/v2/templates/deployment.yaml
This pull request fixes an issue encountered when using `extraEnvs` with the `helm/v2` chart, specifically version 2.20.0. The `indent` level of `10` is `2` levels too deep and causes the yaml parser to fail (see screenshots). Changing this to a level of `8` resolve the issue.
*Pre-requisites*:
* `helm` cli is installed
This can be tested easily by following these steps:
1. Clone the `superblocksteam/agent` repo
2. Change directory into `helm/v2`
3. Edit the `values.yaml` to uncomment the example `extraEnv` values
```yaml
extraEnv: {}
TEST_KEY: foobar
DD_AGENT_HOST:
valueFrom:
fieldRef:
fieldPath: status.hostIP
```
4. Run the following command
```sh
$ helm --dry-run --debug template superblocks-agent . \
-f values.yaml \
--set superblocks.agentDataDomain='app.superblocks.com' \
--set …
```
> Fixes incorrect indent level for extraEnvs include

- helm/v2/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v1.7.2.
> [CI] Bump OPA version in chart to v1.7.2

- helm/v2/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v1.7.3.
> [CI] Bump OPA version in chart to v1.7.3

- helm/v2/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v1.7.4.
> [CI] Bump OPA version in chart to v1.7.4

- helm/v2/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v1.10.1.
> [CI] Bump OPA version in chart to v1.10.1

- helm/v2/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v1.10.2.
> [CI] Bump OPA version in chart to v1.10.2

- helm/v2/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v1.11.0.
> [CI] Bump OPA version in chart to v1.11.0

- helm/v2/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v1.13.0.
> [CI] Bump OPA version in chart to v1.13.0

- helm/v2/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v1.14.0.
> [CI] Bump OPA version in chart to v1.14.0

- helm/agent/Chart.yaml
This reverts commit 71607cdd01943cbced423bd6d970959cd1b681bb.
> Revert "Bump Chart to 1.16.0 (#290)"

- helm/agent/Chart.yaml
Autogenerated PR to bump the App Version in the chart to v1.17.0.
> [CI] Bump OPA version in chart to v1.17.0

- helm/agent/Chart.yaml
This addresses the failing `yamlfmt` check in the default github actions run:
```
- hook id: yamlfmt
- files were modified by this hook
pre-commit hook(s) made changes.
If you are seeing this message in CI, reproduce locally with: `pre-commit run --all-files`.
To run `pre-commit` as part of git workflow, use `pre-commit install`.
All changes made by hooks:
diff --git a/helm/agent/Chart.yaml b/helm/agent/Chart.yaml
index 7de5195..5142ec3 100644
--- a/helm/agent/Chart.yaml
+++ b/helm/agent/Chart.yaml
@@ -1,3 +1,4 @@
+---
apiVersion: v2
appVersion: v1.17.0
description: A Helm chart for the Superblocks On-Prem Agent
```
_(see https://github.com/superblocksteam/agent/actions/runs/12435981140/job/34722901608)_
> Fix `yamlfmt` Errors in Helm Chart
